# Generated by Django 4.2 on 2023-04-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_copies',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.book'),
        ),
        migrations.AlterField(
            model_name='book_copies',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book_loans',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.book'),
        ),
        migrations.AlterField(
            model_name='book_loans',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
