# Generated by Django 4.2 on 2023-04-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_book_copies_book_id_alter_book_copies_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_copies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book_loans',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
